export const ADD_TODO = "ADD_TODO"
export const REMOVE_TODO = "REMOVE_TODO"
export const IS_COMPLETED = "IS_COMPLETED"
export const IS_ACTIVE = "IS_ACTIVE"
export const CLEAR_COMPLETED = "CLEAR_COMPLETED"
export const FILTER_TODO = "FILTER_TODO"
export const START_EDIT = "START_EDIT"
export const END_EDIT = "END_EDIT"
